[package]
name = "sunkenball/unify"
description = "A powerful framework for building Roblox games:\n\nhttps://unify.rocks"
version = "1.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["sunken", "gemtool"]

[dependencies]
